name: Deploy
run-name: ${{ github.actor }} deployed new version
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Move node_modules to lib
        run: mv node_modules lib/node_modules

      - name: Move package.json to lib
        run: mv package.json lib/package.json

      - name: Zip
        run: (cd lib && zip -r ../function.zip .)

      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: alexaskill1
          zip_file: function.zip
